version: '3.1'

services:

  wordpress:
    image: wordpress:5.0
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'

  nginx:
    image: nginx 
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx/index.html:/usr/share/nginx/html/index.html
      - ./nginx/iframe-post.html:/usr/share/nginx/html/iframe-post.html


